bot:
  # get bot token from https://t.me/botfather
  token: 7609365027:AAFlxoETy1_JB4TXxcgWeaLOPtEMfNZkxb0

# chat id for redirect messages
chat_id: -1002357907259

# Fill variables below as you want, or use default values.
# You can use HTML tags provided by the sulguk package.
# https://github.com/Tishka17/sulguk#readme

messages:
    notify_user_about_success_deliver: ✅ Ожидайте ответа.
    help_message: |
     <h1>
      👋 Добрый день!
      </h1>
      <p>
          Я могу передать Ваше обращение администрации СНТ.
      </p>

      <p>
       Отправьте свое обращение здесь и ждите ответа в личных сообщениях. Обращения рассматриваются в течении 1-2 рабочих дней. !
      </p>
    notify_admin_about_success_answer: ✅ Ответ дан.

errors:
  unsupported_type: ❌ Unsupported message type.<br/>Please check <b>/help</b> command.
  too_long_message_text: ❌ Too long message text.
  too_long_message_caption: ❌ Too long message caption.
  copy_message: ❌ Error during copying
  extract_user_id: ❌ Error during extract_id
  chat_not_found: ❌ Chat not found. Make sure you have added the bot to the admin group
